### PR TITLE
Emoji menu x-axis overflow fix.

### PR DESCRIPTION
**Pull request by cosmicAsymmetry**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Merged as b09995c with changed author; we prefer real mail addresses.  Let me know if you would like a different mail address used.

**Comment by cosmicAsymmetry** [comment]
That is my real email address(http://sidhant.me/). Although, I also use my G-Mail - bhavnanisidhant@gmail.com

Thanks for the merge!
Regards,
Sidhant

**Comment by quozl** [comment]
You may be interested in https://github.com/sugarlabs/chat/commit/0f09a26681f01b484efa67ebda06e869c44f5e3d which solves the problem for other GTK+ versions.

**Comment by cosmicAsymmetry** [comment]
Interesting. Thanks for sharing @quozl! 😄

**Pull request closed without merging**
