### PR TITLE
Implement the Search feature for the activity

### PR DESCRIPTION
**Pull request by nswarup14**
Implements #18 
**Changes**
1. `activity.py`
2. `box.py`

**Feature**
1. The 'Search Entry' widget is added to the activity that enables one to search the chat log and highlight the matched the text which matches with the query.
2. The 'Previous' and 'Next' buttons are added that enable one to search next and highlight the results in different background colours.

**Improvements**
1. On searching a particular string for the very first time, the 'Next' widget is disabled, however, the 'Previous' widget is enabled. It should have been the be the opposite. However, after a couple of initial clicks, the widgets seem to work alright.

2. Add shortcuts to perform the relevant tasks.

I shall implement the second point under **Improvements** as soon as possible. I am quite unable to figure out the first point even after much debugging. I welcome others to test and review the changes and suggest further improvements as well.

Thanks.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tested 804d6b7 on Ubuntu 18.04.

I agree, as you mentioned,

* [ ] when one match is found, the previous button is enabled,
* [ ] there's an opportunity to add <kbd>ctrl</kbd>+<kbd>f</kbd> and <kbd>ctrl</kbd>+<kbd>g</kbd> shortcuts,

Also, when the text flow contains five mentions of a word spread across three transmissions by two people, only the first two matches could be highlighted in cyan using the previous and next buttons.  All five mentions were highlighted in red.  I didn't test other combinations.

**Comment by nswarup14** [comment]
@quozl Thanks
> Also, when the text flow contains five mentions of a word spread across three transmissions by two people, only the first two matches could be highlighted in cyan using the previous and next buttons. All five mentions were highlighted in red. I didn't test other combinations.

Wouldn't it be better to highlight all the occurrences of the text? That way the user can focus on the message he is searching for.

**Comment by quozl** [comment]
Yes, all occurrences should be highlighted, and all should be selectable using the previous and next buttons.  At the moment, in 804d6b7, all occurrences are highlighted, but not all are selectable using the buttons.

**Comment by chimosky** [comment]
> Yes, all occurrences should be highlighted, and all should be selectable using the previous and next buttons. At the moment, in [804d6b7](https://github.com/sugarlabs/chat/commit/804d6b71f6b45f0b80ddf92186c795af7f359470), all occurrences are highlighted, but not all are selectable using the buttons.

Tested and found the same issue, and the `previous` button is never enabled when any text is found.

**Comment by nswarup14** [comment]
@chimosky
Thanks!
The patch is still in progress. I've not been able to fully test it yet, because I'm running into issues while setting up collaboration.

I shall keep the above in mind when I begin testing.

**Comment by Aniket21mathur** [comment]
Thanks. Tested. Works as expected. :smile: .

**Comment by nswarup14** [comment]
@Aniket21mathur 
Thanks!

**Updates**
1) Two tags to highlight all possible matches. The cyan tag indicates the current match in focus and the red indicates all the matches found. To iterate between matches, use the `previous` and the `buttons`.
2) Unlike `Gtk.TextIter` iterators, `Gtk.TextMark` marks remain valid across buffer mutations, because their behavior is defined when text is inserted or deleted. Hence I insert two marks by the name 'start' and 'end' the ends of the cyan tag. As and when the focus on the highlighted text changes, by pressing `next` and `previous`, I update the marks individually.
3) When the next or previous match is in another textBox (each blob of text represents a Gtk.TextView object), I delete the present marks and create new ones in the corresponding TextBox. That way, the activity saves just two marks at any given point in time. This would avoid a flood of marks which can overlap on different searches.
4) Upon changing the search entry, the `changed` signal handler ensures that any existing marks for the previous search is removed.

Thanks!

**Comment by chimosky** [comment]
Thanks, tested. 

When focus is changed to another match, the previous match is still in cyan instead of red. 
So when you move through all matches it's hard to tell which has focus.

**Comment by nswarup14** [comment]
@chimosky 
Does this happen on clicking `next` or `previous`?

**Comment by nswarup14** [comment]
@chimosky 
Thanks
I had overlooked the part where the cyan tags are being removed. 
I have now updated the code such that on iterating through the matches, the earlier cyan tags are removed globally, from all the textboxes. This way I do not have to store from which textbox the earlier cyan tag needs to be removed.

**Comment by chimosky** [comment]
Tested, effect remains the same.
It'll be great if the search is initiated once the user enters text instead of having to press `enter`.

**Comment by nswarup14** [comment]
@chimosky 
Thanks
> It'll be great if the search is initiated once the user enters text instead of having to press `enter`.

Do you mean when the text is entered in the search box, or in the textbox down below?

**Comment by chimosky** [comment]
When text is entered in the search entry.

**Comment by nswarup14** [comment]
I was able to finally get collaboration running as I explained [here](http://lists.sugarlabs.org/archive/sugar-devel/2019-July/057045.html), especially thanks to @chimosky suggestions.

However I am unable get the desired behavior, and I'm unable to figure out anything wrong in the code.

1) To the search entry's `changed` signal, I have attached the callback that initiates the search as the characters are entered. However that feature is not being shown on running the activity.
2) I also remove all the cyan tags from all the `Gtk.TextView` message boxes, before updating the next search match. Yet, the tags are not being removed as expected on running the activity.

The log file shows something like `Gtk-CRITICAL gtk_text_buffer_remove_tag_by_name assertion gtk_text_iter_get_buffer (start) == buffer failed`.

I'm unable to move past this. However, I had tried testing the activity earlier on v0.114 Sugar desktop on a Ubuntu 18.04 VM, with just one user and both the features working alright. They dont seem to work in collaboration, although I have not tampered with the underlying Telepathy configuration.

Request help
Thanks

**Comment by chimosky** [comment]
Tested, quits when 'a' or 'q' is entered in the search. 
Log file shows
```
Gtk-CRITICAL **: gtk_text_buffer_get_iter_at_mark: assertion '!gtk_text_mark_get_deleted (mark)' failed
```

I can't investigate further at the moment, the change you made to `chat/box.py` did you test it?, as in 9961351 nothing changed except the callback, and the change you made in `chat/box.py`.

**Comment by nswarup14** [comment]
@quozl @chimosky 
I identified the error that I outlined in the above [comment](https://github.com/sugarlabs/chat/pull/19#issuecomment-508800029). I was using the wrong identifier name to remove tags, which I have corrected in https://github.com/sugarlabs/chat/pull/19/commits/537b613f284983ef531f3f823e53356da93d07b6.

The search feature works as expected now. The tags are replaced and new ones are created correctly.
Tested on Sugar Live Build with v0.114 via collaboration.

I have also refactored code that access private data members directly using the `. (dot)` operator, which is bad practice.

I have also rebased this branch against the current _master_. Please review.

Thanks.

**Comment by quozl** [comment]
Thanks.  Tested f038e47 on Ubuntu 19.04 with collaboration.

The search works.  The feature is proceeding well.  Please continue.  Yet to do at least;

* [ ] when a search is made, the scrollback position is not changed to show it, see issue,
* [ ] when newly matching text appears in the log, the search is not updated,
* [ ] the keyboard shortcuts mentioned in the issue are pending,
* [ ] there are 39 new flake8 messages,
* [ ] the toolbar is no longer empty, and the next and previous buttons do not fit on 1024x768 display resolution, so also revert 95170aa7bc78f2f5a57c56cfab0ec974e96b404b.

**Comment by quozl** [comment]
While testing 6a11f7d, a segmentation fault happened at about the same time I began typing "four" into the text entry box.  org.laptop.Chat-1.log contains;

```
(sugar-activity:2018): Pango-WARNING **: 10:43:03.873: failed to create cairo scaled font, expect ugly output. the offending font is 'Noto Color Emoji 109'

(sugar-activity:2018): Pango-WARNING **: 10:43:03.873: font_face status is: file not found

(sugar-activity:2018): Pango-WARNING **: 10:43:03.873: scaled_font status is: file not found

(sugar-activity:2018): Pango-WARNING **: 10:43:03.873: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Noto Color Emoji 109', text='✌'

(sugar-activity:2018): Gtk-CRITICAL **: 10:43:26.524: gtk_text_buffer_get_iter_at_mark: assertion '!gtk_text_mark_get_deleted (mark)' failed
Terminated by signal 11, pid 2018 data (<open file '<fdopen>', mode 'w' at 0x7f2ae2f89e40>, '7cbaaedf442aa45f599c357f9f1db69e7e417528')
```

Why does "f" do this?  Conditional of the key press handler looks wrong; CONTROL_MASK is not a boolean.

Why does it crash?  No idea, I'll leave you to look into that.

**Comment by nswarup14** [comment]
@quozl
Yes, I'm getting a similar segmentation fault.
I am trying to preserve the history of the current highlighted tag, so that
when a new entry is added to the chat, the search does not begin from start.
However, I might have implemented this wrong.

I shall debug this further and add more commits as soon as possible.

Thanks.

>

**Comment by nswarup14** [comment]
@quozl @chimosky 
I have removed the segmentation fault and the activity runs fine now.
I have also added the shortcuts for various actions.

I am facing issue in the following
1) On entering a new word, the search is initiated once again
2) I'm not sure how to change the scrollback position, on search. I tried the following ways, but none succeeded.

- Emit a signal on updating the cyan tag. Connect a handler to the signal, which scrolls till the textview object, that has the cyan tag, comes on the screen. Doing this however, causes the scroll to go **to the top** everytime a new text is entered below, because the search is started once again.

Thanks.

**Comment by quozl** [comment]
Fixes #18.

**Comment by quozl** [comment]
Thanks.  Merged by hand with review comments.  Tested.

**Pull request closed without merging**
